spring:
  application:
    name: sdi

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sdi}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
